config/routes.rb
Juvius::Application.routes.draw do

  
  
  devise_for :users
  
  resources :workproducts
  resources :users do
    get 'users', :to => 'workproducts#new', :as => :user_root
  end

  root :to => "welcome#show"
  
  match ':public_id' => 'users#show'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :workproducts
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email,:username, :password, :password_confirmation, :remember_me, :public_id


end

app/models/workproduct.rb
class Workproduct < ActiveRecord::Base
  has_one :user
  
  attr_accessible :user_id, :workname, :worktype, :description, :tehnology
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 

  def show
    @user = User.find_by_public_id(params[:public_id])
    
    if !@user.blank? 
        @user_workproducts = Workproduct.find(:all, :conditions => ["user_id = ?", @user.id])
    end
    
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController


  def show
    
  end

end

app/controllers/workproducts_controller.rb
class WorkproductsController < ApplicationController
  before_filter :authenticate_user! , :only => [:new]

  def index
    @workproducts = Workproduct.all
  end

  def show
    @workproduct = Workproduct.find(params[:id])
  end

  def new
    @workproduct = Workproduct.new
  end

  def create
    @workproduct = Workproduct.new(params[:workproduct])
    if @workproduct.save
      redirect_to new_workproduct_path, :notice => "Successfully created workproduct."
    else
      render :action => 'new'
    end
  end

  def edit
    @workproduct = Workproduct.find(params[:id])
  end

  def update
    @workproduct = Workproduct.find(params[:id])
    if @workproduct.update_attributes(params[:workproduct])
      redirect_to @workproduct, :notice  => "Successfully updated workproduct."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @workproduct = Workproduct.find(params[:id])
    @workproduct.destroy
    redirect_to workproducts_url, :notice => "Successfully destroyed workproduct."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/workproducts_helper.rb
module WorkproductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    
    <div id="container">
    <div id="user_nav">
    <% if user_signed_in? %>
        Signed in as <%= current_user.email %>. Not you?
       <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
       <%= link_to "New workproduct", new_workproduct_path %>
       <%= "Public Id: " + current_user.public_id %>
    <% else %>
        <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
    <% end %>
    </div>
    <br>
    <h1><strong>Juvious</strong></h1>

       
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      

    
      <div style="width:500px; margin:50px auto;padding: 40px; border: 1px solid #CCCCCC; box-shadow: 0 0 30px #CCCCCC;">
        <%= yield %>
     </div>
    </div>
  </body>
</html>

app/views/users/show.html.erb
<%if (@user == nil)%>
  <% title 'No public ID found' %>
<%else%>
  <% title @user.username %>
<%end%>

<% debug @user_workproducts%>
<% debug @user%>

<% if @user.blank? or @user_workproducts.blank? %>
    No Workproducts
    
<% else %>
    <% debug @user_workproducts%>
    
    <% for workproduct in  @user_workproducts do %>
    <p>
      <strong>Workname:</strong>
      <%= link_to workproduct.workname , workproduct_path(workproduct) %> <%= workproduct.worktype %> <%= workproduct.description %> 
      <% if current_user == workproduct.user_id %>
          <%= link_to "Edit", edit_workproduct_path(workproduct) %> |
          <%= link_to "Destroy", workproduct, :confirm => 'Are you sure?', :method => :delete %> |
      <% end %>
    </p>
    <% end %>
<% end %>

<p>

</p>

app/views/welcome/show.html.erb
<div style="text-align:center">
<p>
   Show your work to the world
</p>
<p>
  <% if current_user.nil? %>
    <%= link_to "Sign in" , new_user_session_path %>    or     <%= link_to "Register" , new_user_registration_path %>
  <%else%>
    Wellcome to Juvius.
  <%end%>
  
</p>
</div>

</p>

app/views/workproducts/_form.html.erb
<%= form_for @workproduct do |f| %>
  <%= f.error_messages %>

  <%= f.hidden_field :user_id, :value => current_user.nil? ? nil : current_user.id%>

  <p>
    <%= f.label :workname %><br />
    <%= f.text_field :workname %>
  </p>
  <p>
    <%= f.label :worktype %><br />
    <%= f.text_field :worktype %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :tehnology %><br />
    <%= f.text_field :tehnology %>
  </p>
  <p><%= f.submit %></p>
  
<% end %>

app/views/workproducts/edit.html.erb
<% title "Edit Workproduct" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @workproduct %> |
  <%= link_to "View All", workproducts_path %>
</p>

app/views/workproducts/index.html.erb
<% title "Workproducts" %>

<table>
  <tr>
    <th>User</th>
    <th>Workname</th>
    <th>Type</th>
    <th>Description</th>
    <th>Tehnology</th>
  </tr>
  <% for workproduct in @workproducts %>
    <tr>
      <td><%= workproduct.user_id %></td>
      <td><%= workproduct.workname %></td>
      <td><%= workproduct.worktype %></td>
      <td><%= workproduct.description %></td>
      <td><%= workproduct.tehnology %></td>
      <td><%= link_to "Show", workproduct %></td>
      <td><%= link_to "Edit", edit_workproduct_path(workproduct) %></td>
      <td><%= link_to "Destroy", workproduct, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Workproduct", new_workproduct_path %></p>

app/views/workproducts/new.html.erb
<% title "New Workproduct" %>

<%= render 'form' %>

<p><%#= link_to "Back to List", workproducts_path %></p>

app/views/workproducts/show.html.erb
<% title "Workproduct" %>

<p>
  <strong>Workname:</strong>
  <%= @workproduct.workname %>
</p>
<p>
  <strong>Type:</strong>
  <%= @workproduct.worktype %>
</p>
<p>
  <strong>Description:</strong>
  <%= @workproduct.description %>
</p>
<p>
  <strong>Tehnology:</strong>
  <%= @workproduct.tehnology %>
</p>

<p>

  <% if !current_user.blank? and current_user.id == @workproduct.user_id %>
      <%= link_to "Edit", edit_workproduct_path(@workproduct) %> |
      <%= link_to "Destroy", @workproduct, :confirm => 'Are you sure?', :method => :delete %> |
      <%#= link_to "View All", workproducts_path %>
  <%end%>
</p>